### ISSUE TITLE
Repository-related improvements

### ISSUE THREAD

**Issue by hrszpuk** [hrszpuk/bytespace.py#3]
## Description
Adding repository related improvements so make the project more professional and easier to manage/contribute to.

## Tasks
- [x] New labels
- [x] Issue templates
- [x] Pull request templates
- [x] Code of Conduct
- [x] Contributing guidelines
- [x] CodeQL
- [x] Labeler
- [x] Discussions
- [x] Sponsor Page
- [x] Security Vulnerability Report
- [x] Logger milestone
- [x] Move documentation out of `README.md` and into `docs/`
- [x] Improve `README.md`
    - [x] shield.io tags
    - [x] Contrib.rocks
    - [x] Link to `docs/`
- [x] Add dev documentation to `docs/`

**Comment by hrszpuk** [comment]
Let's do this 😎

**Comment by hrszpuk** [comment]
DONE!
